
FROM node:24.2.0-bookworm-slim

WORKDIR /usr/src/app

# Open ssl required for prisma in docker.
RUN apt-get update -y \
  && apt-get install -y openssl \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm

COPY package.json pnpm-workspace.yaml* .npmrc* ./

RUN pnpm install

COPY . .

RUN pnpm prisma generate

RUN pnpm run build


