version: "3.9"

services:
  api:
    image: dahalsaroj/nch-cms-backend:latest
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
