export enum ROLE {
  USER = "USER",
  ADMIN = "ADMIN",
  CONTENT_ADMIN = "CONTENT_ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum USER_TYPE {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  CONTENT_ADMIN = "CONTENT_ADMIN",
  ORGANIZATION = "ORGANIZATION",
  INDIVIDUAL = "INDIVIDUAL",
}
